### ISSUE TITLE
Validate availability of hardware backed key store

### ISSUE THREAD

**Issue by kneckinator** [idpass/mimoto#2]
See https://source.android.com/security/keystore/attestation

**Comment by rjmangubat23** [comment]
**Backend Estimate**

Sample testing of validity in Android Native code: .5 days 

Note: For React Native it is available in expo: https://docs.expo.dev/versions/latest/sdk/securestore/ but will do more checking on validity

**Comment by rjmangubat23** [comment]
WIP:
- Due to Expo ejection, we can't use [securestore](https://docs.expo.dev/versions/latest/sdk/securestore/ ) easily. So I am currently experimenting on either [Secure Shared Preferences](https://reactnative.dev/docs/security#android---secure-shared-preferences) or [Android Keystore](https://reactnative.dev/docs/security#android---keystore) in the SafetyNet POC

**Comment by rjmangubat23** [comment]
Backend is already available but still needs to be implemented via frontend by integrating SafetyNet APIs.
